name: CI
on: [push]
jobs:
  codeValidation:
    name: ESLint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm run test
